### ISSUE TITLE
make default subscribers and mailservers optional

### ISSUE THREAD

**Issue by vkhatri** [bbg-cookbooks/monit-ng#15]
hello! i am trying to manage monit configuration alone with chef role, but facing some issues.

1. localhost is always set to first mailserver, where i want to configure it to something else for different location servers and the only way i get it right is overriding attribute in a chef role, but that does not get me so far as i need different config for different chef roles

2. default root subscribers does not help my scenario much, at some places even local smtp is disabled

what do you think about having an attribute e.g. `default['monit']['default_config']`? which if set true, then  below attributes will get default values otherwise not:

default['monit']['config']['subscribers']
default['monit']['config']['mail_servers']

i have PR ready if this sound good to you.

**Comment by nathwill** [comment]
i'm not quite sure i understand the use case here.

as far as i know, both the subscribers and mailservers configurations should be able to be excluded from the generated configuration by setting the attributes to an empty array, or overriden from a wrapping cookbook.

i just verified that overriding from a wrapper cookbook works like i thought (check the mail-server-subscriber-override branch for an example).

does that help with what you're trying to achieve, or am i misunderstanding?

**Comment by vkhatri** [comment]
I am using chef roles for now and monit checks recipe provided by this
cookbook.

as chef role default attributes takes precedence over cookbook and
environment default attributes, I don't have to user override anywhere. Now
it may seems weird, but it's one of the standard we have adopted to
maintain attributes among cookbook and roles.

this helps at some places to perform an audit or regular clean up, as we
know that we always just have to look for default attributes not override.
And if I use override attributes, I will have to maintain
override_attributes everywhere for each app role where I want to use monit
and believe me it makes things bit uneasy for us.

but you are right, override works just fine.

also monit default config does not set any subscribers or mail servers, I
would like cookbook to be able to provide a basic config as possible with
configurable option.

**Comment by nathwill** [comment]
OK, I think I understand. For your role-centric use case, Chef is merging the options instead of allowing them to be overridden with the same attribute precedence (ouch).

I confess I'm not a big fan of the proposed solution of a boolean that only controls certain configuration options, as it seems like it would generate some confusion, but I do think the cookbook should reflect the upstream configuration defaults as much as possible, so thanks for bringing that up.

A better solution here might be to update the cookbook attribute defaults for subscribers and mail_servers to each be empty arrays, and move the current values into the README to document how to set them for users that wish to use them.

Does that sound like a reasonable solution? If so, I'd welcome a PR for it.

**Comment by vkhatri** [comment]
@nathwill setting both the value to an empty array would be ideal, i just did not want to propose it at first place considering the default use case.

submitting a PR. thanks!

**Comment by vkhatri** [comment]
@nathwill submitted https://github.com/bbg-cookbooks/monit-ng/pull/17

also added some extra content to README, i hope you don't mind.

**Comment by nathwill** [comment]
not a bit, thank you very much! this is merged now, so closing out the issue. i'm going to run this through it's integration tests and address issue #18 before cutting a new release (likely tomorrow or the day after).

thanks again for all the help!
