### ISSUE TITLE
start/stop command limits

### ISSUE THREAD

**Issue by alvaromorales** [bbg-cookbooks/monit-ng#43]
A 127-character limit for start/stop commands was added in https://github.com/bbg-cookbooks/monit-ng/commit/22c6eef0b055f163267055e228e81eb282df717a. For some use cases I'm having to wrap long commands in a shell script because. Is the limit still necessary?

I'm running Monit 5.6 and have not seen any issues with commands being truncated.

**Comment by nathwill** [comment]
well, it's an interesting question that seems to come up from time to time. i'm not 100% sure whether it still applies or not, but the most recent [reference](http://comments.gmane.org/gmane.comp.monitoring.monit.general/7151) to the limit is from just last year.

my gut feeling on it so far is that:

- since the cookbook supports monit versions known to suffer the problem
- since commands that long are fairly rare and usually belong in a wrapper script that gets called from monit instead
- since this has the potential to bite people, and the limit's not well advertised in the docs

then, it's preferable to keep it in the cookbook. That said, i'm open to changing my mind if circumstances change. do you have an example of a type of command that you're running into the limit for?

**Comment by alvaromorales** [comment]
Trying to execute a jar with a long classpath (easily longer than 127 chars).

> since commands that long are fairly rare and usually belong in a wrapper script that gets called from monit instead

I think this is reasonable. It does involves additional steps in Chef like creating a dir for wrapper scripts and creating a file with the long command. I just wish monit had better documentation around the 127-char limit. Thanks!

**Comment by nathwill** [comment]
My pleasure, thanks for the feedback!
